/* Generated by the Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */

var framePtr = null;
var excHandler = 0;
var lastJSError = null;
if (typeof Int8Array === 'undefined') Int8Array = Array;
if (typeof Int16Array === 'undefined') Int16Array = Array;
if (typeof Int32Array === 'undefined') Int32Array = Array;
if (typeof Uint8Array === 'undefined') Uint8Array = Array;
if (typeof Uint16Array === 'undefined') Uint16Array = Array;
if (typeof Uint32Array === 'undefined') Uint32Array = Array;
if (typeof Float32Array === 'undefined') Float32Array = Array;
if (typeof Float64Array === 'undefined') Float64Array = Array;
var NTI140 = {size: 0,kind: 29,base: null,node: null,finalizer: null};
var NTI57005 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NTI57003 = {size: 0,kind: 22,base: null,node: null,finalizer: null};
var NTI57220 = {size: 0,kind: 24,base: null,node: null,finalizer: null};
var NTI124 = {size: 0,kind: 36,base: null,node: null,finalizer: null};
var NTI42021 = {size: 0, kind: 18, base: null, node: null, finalizer: null};
var NNI42021 = {kind: 2, len: 2, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "x", len: 0, typ: NTI124, name: "x", sons: null}, 
{kind: 1, offset: "y", len: 0, typ: NTI124, name: "y", sons: null}]};
NTI42021.node = NNI42021;
var NNI57005 = {kind: 2, len: 3, offset: 0, typ: null, name: null, sons: [{kind: 1, offset: "pt", len: 0, typ: NTI42021, name: "pt", sons: null}, 
{kind: 1, offset: "size", len: 0, typ: NTI124, name: "size", sons: null}, 
{kind: 1, offset: "color", len: 0, typ: NTI140, name: "color", sons: null}]};
NTI57005.node = NNI57005;
NTI57003.base = NTI57005;
NTI57220.base = NTI57003;

function setConstr() {
		      var result = {};
      for (var i = 0; i < arguments.length; ++i) {
        var x = arguments[i];
        if (typeof(x) == "object") {
          for (var j = x[0]; j <= x[1]; ++j) {
            result[j] = true;
          }
        } else {
          result[x] = true;
        }
      }
      return result;
    

	
}
var ConstSet1 = setConstr(17, 16, 4, 18, 27, 19, 23, 22, 21);

function nimCopy(dest_19817, src_19818, ti_19819) {
	var result_20229 = null;

		switch (ti_19819.kind) {
		case 21:
		case 22:
		case 23:
		case 5:
			if (!(isFatPointer_19801(ti_19819))) {
			result_20229 = src_19818;
			}
			else {
				result_20229 = [src_19818[0], src_19818[1]];
			}
			
			break;
		case 19:
			      if (dest_19817 === null || dest_19817 === undefined) {
        dest_19817 = {};
      }
      else {
        for (var key in dest_19817) { delete dest_19817[key]; }
      }
      for (var key in src_19818) { dest_19817[key] = src_19818[key]; }
      result_20229 = dest_19817;
    
			break;
		case 18:
		case 17:
			if (!((ti_19819.base == null))) {
			result_20229 = nimCopy(dest_19817, src_19818, ti_19819.base);
			}
			else {
			if ((ti_19819.kind == 17)) {
			result_20229 = (dest_19817 === null || dest_19817 === undefined) ? {m_type: ti_19819} : dest_19817;
			}
			else {
				result_20229 = (dest_19817 === null || dest_19817 === undefined) ? {} : dest_19817;
			}
			}
			nimCopyAux(result_20229, src_19818, ti_19819.node);
			break;
		case 24:
		case 4:
		case 27:
		case 16:
			      if (src_19818 === null) {
        result_20229 = null;
      }
      else {
        if (dest_19817 === null || dest_19817 === undefined) {
          dest_19817 = new Array(src_19818.length);
        }
        else {
          dest_19817.length = src_19818.length;
        }
        result_20229 = dest_19817;
        for (var i = 0; i < src_19818.length; ++i) {
          result_20229[i] = nimCopy(result_20229[i], src_19818[i], ti_19819.base);
        }
      }
    
			break;
		case 28:
			      if (src_19818 !== null) {
        result_20229 = src_19818.slice(0);
      }
    
			break;
		default: 
			result_20229 = src_19818;
			break;
		}

	return result_20229;

}

function makeNimstrLit(c_14603) {
		    var ln = c_14603.length;
    var result = new Array(ln + 1);
    var i = 0;
    for (; i < ln; ++i) {
      result[i] = c_14603.charCodeAt(i);
    }
    result[i] = 0; // terminating zero
    return result;
    

	
}

function toJSStr(s_15003) {
		    var len = s_15003.length-1;
    var asciiPart = new Array(len);
    var fcc = String.fromCharCode;
    var nonAsciiPart = null;
    var nonAsciiOffset = 0;
    for (var i = 0; i < len; ++i) {
      if (nonAsciiPart !== null) {
        var offset = (i - nonAsciiOffset) * 2;
        var code = s_15003[i].toString(16);
        if (code.length == 1) {
          code = "0"+code;
        }
        nonAsciiPart[offset] = "%";
        nonAsciiPart[offset + 1] = code;
      }
      else if (s_15003[i] < 128)
        asciiPart[i] = fcc(s_15003[i]);
      else {
        asciiPart.length = i;
        nonAsciiOffset = i;
        nonAsciiPart = new Array((len - i) * 2);
        --i;
      }
    }
    asciiPart = asciiPart.join("");
    return (nonAsciiPart === null) ?
        asciiPart : asciiPart + decodeURIComponent(nonAsciiPart.join(""));
  

	
}
var nimvm_6119 = false;
var nim_program_result = 0;
var globalRaiseHook_11605 = [null];
var localRaiseHook_11610 = [null];
var outOfMemHook_11613 = [null];
var IDMATRIX_42056 = matrix2d_42040(1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, 0.0, 0.0);
var ORIGO_42057 = point2d_42052(0.0, 0.0);
var XAXIS_42058 = vector2d_42048(1.0000000000000000e+000, 0.0);
var YAXIS_42059 = vector2d_42048(0.0, 1.0000000000000000e+000);
var state_47605 = [{a0: 1773455756, a1: 4275166512}];

function getTime_50042() {
	var result_52413 = 0.0;

	BeforeRet: do {
		result_52413 = new Date();
		break BeforeRet;
	} while (false);

	return result_52413;

}
var startMilsecs_52512 = [getTime_50042()];

function rotl_47802(x_47804, k_47805) {
	var result_47806 = 0;

		result_47806 = ((x_47804 << k_47805) | ((x_47804 >>> 0) >>> ((64 - k_47805) >>> 0)));

	return result_47806;

}

function next_47842(s_47845) {
	var result_47846 = 0;

		var s0_47847 = s_47845.a0;
		var s1_47848 = s_47845.a1;
		result_47846 = ((s0_47847 + s1_47848) >>> 0);
		s1_47848 = (s1_47848 ^ s0_47847);
		s_47845.a0 = ((rotl_47802(s0_47847, 55) ^ s1_47848) ^ (s1_47848 << 14));
		s_47845.a1 = rotl_47802(s1_47848, 36);

	return result_47846;

}

function randomize_48434(seed_48436) {
		state_47605[0].a0 = ((seed_48436 ) >>> 16);
		state_47605[0].a1 = (seed_48436 & 65535);
		next_47842(state_47605[0]);

	
}

function randomize_53001() {
		randomize_48434(getTime_50042().getTime());

	
}

function newSeq_57235(len_57239) {
	var result_57241 = null;

		result_57241 = new Array(len_57239); for (var i=0;i<len_57239;++i) {result_57241[i]=null;}
	return result_57241;

}

function random_48318(max_48320) {
	var result_48321 = 0.0;

		var x_48323 = next_47842(state_47605[0]);
		result_48321 = ((x_48323 / 4294967295) * max_48320);

	return result_48321;

}

function new_57275() {
	var result_57280 = null;

	BeforeRet: do {
		var r_57401 = null;
		r_57401 = {pt: {x: 0.0, y: 0.0}, size: 0.0, color: null};
		result_57280 = r_57401;
		break BeforeRet;
	} while (false);

	return result_57280;

}

function point2d_42052(x_42054, y_42055) {
	var result_42918 = {x: 0.0, y: 0.0};

		result_42918.x = x_42054;
		result_42918.y = y_42055;

	return result_42918;

}

function isFatPointer_19801(ti_19803) {
	var result_19804 = false;

	BeforeRet: do {
		result_19804 = !((ConstSet1[ti_19803.base.kind] != undefined));
		break BeforeRet;
	} while (false);

	return result_19804;

}

function nimCopyAux(dest_19822, src_19823, n_19825) {
		switch (n_19825.kind) {
		case 0:
			break;
		case 1:
			      dest_19822[n_19825.offset] = nimCopy(dest_19822[n_19825.offset], src_19823[n_19825.offset], n_19825.typ);
    
			break;
		case 2:
			L1: do {
				var i_20215 = 0;
				var colontmp__20217 = 0;
				colontmp__20217 = (n_19825.len - 1);
				var res_20220 = 0;
				L2: do {
						L3: while (true) {
						if (!(res_20220 <= colontmp__20217)) break L3;
							i_20215 = res_20220;
							nimCopyAux(dest_19822, src_19823, n_19825.sons[i_20215]);
							res_20220 += 1;
						}
				} while(false);
			} while(false);
			break;
		case 3:
			      dest_19822[n_19825.offset] = nimCopy(dest_19822[n_19825.offset], src_19823[n_19825.offset], n_19825.typ);
      for (var i = 0; i < n_19825.sons.length; ++i) {
        nimCopyAux(dest_19822, src_19823, n_19825.sons[i][1]);
      }
    
			break;
		}

	
}

function makeSnow_57212(n_57214, width_57215, height_57216) {
						var Tmp4;

	var result_57218 = null;

	BeforeRet: do {
		randomize_53001();
		var snows_57259 = newSeq_57235(n_57214);
		L1: do {
			var i_57271 = 0;
			var colontmp__57416 = 0;
			colontmp__57416 = (n_57214 - 1);
			var res_57419 = 0;
			L2: do {
					L3: while (true) {
					if (!(res_57419 <= colontmp__57416)) break L3;
						i_57271 = res_57419;
						var size_57272 = (random_48318(1.0000000000000000e+000) * 2.2000000000000000e+001);
						var snow_57410 = new_57275();
						nimCopy(snow_57410.pt, point2d_42052(random_48318(width_57215), random_48318(height_57216)), NTI42021);
						snow_57410.size = size_57272;
						if ((size_57272 < 5.0000000000000000e+000)) {
						Tmp4 = makeNimstrLit("#A0A0A0");
						}
						else {
						if ((size_57272 < 1.0000000000000000e+001)) {
						Tmp4 = makeNimstrLit("#C0C0C0");
						}
						else {
						if ((size_57272 < 1.5000000000000000e+001)) {
						Tmp4 = makeNimstrLit("#E0E0E0");
						}
						else {
						Tmp4 = makeNimstrLit("#FFFFFF");
						}
						}}
						snow_57410.color = toJSStr(Tmp4);
						snows_57259[i_57271] = snow_57410;
						res_57419 += 1;
					}
			} while(false);
		} while(false);
		result_57218 = nimCopy(null, snows_57259, NTI57220);
		break BeforeRet;
	} while (false);

	return result_57218;

}

function median3_57457(x_57461, y_57463, z_57465) {
	var result_57466 = 0.0;

	BeforeRet: do {
		if ((x_57461 < y_57463)) {
		if ((y_57463 < z_57465)) {
		result_57466 = y_57463;
		break BeforeRet;
		}
		else {
		if ((z_57465 < x_57461)) {
		result_57466 = x_57461;
		break BeforeRet;
		}
		else {
			result_57466 = z_57465;
			break BeforeRet;
		}
		}
		}
		else {
			if ((z_57465 < y_57463)) {
			result_57466 = y_57463;
			break BeforeRet;
			}
			else {
			if ((x_57461 < z_57465)) {
			result_57466 = x_57461;
			break BeforeRet;
			}
			else {
				result_57466 = z_57465;
				break BeforeRet;
			}
			}
		}
		
	} while (false);

	return result_57466;

}

function quicksort_57436(list_57440, list_57440_Idx, left_57441, right_57442) {
	BeforeRet: do {
		var diff_57443 = (right_57442 - left_57441);
		if ((diff_57443 <= 0)) {
		break BeforeRet;
		}
		else {
		if ((diff_57443 == 1)) {
		if ((list_57440[list_57440_Idx][left_57441].size <= list_57440[list_57440_Idx][right_57442].size)) {
		break BeforeRet;
		}
		else {
			var Tmp1 = list_57440[list_57440_Idx][left_57441]; list_57440[list_57440_Idx][left_57441] = list_57440[list_57440_Idx][right_57442]; list_57440[list_57440_Idx][right_57442] = Tmp1;			break BeforeRet;
		}
		
		}
		else {
			var i_57454 = left_57441;
			var j_57455 = right_57442;
			var pivot_57467 = median3_57457(list_57440[list_57440_Idx][i_57454].size, list_57440[list_57440_Idx][(i_57454 + Math.floor((j_57455 - i_57454) / 2))].size, list_57440[list_57440_Idx][j_57455].size);
			L2: do {
					L3: while (true) {
					if (!true) break L3;
						L4: do {
								L5: while (true) {
								if (!(list_57440[list_57440_Idx][i_57454].size < pivot_57467)) break L5;
									i_57454 += 1;
								}
						} while(false);
						L6: do {
								L7: while (true) {
								if (!(pivot_57467 < list_57440[list_57440_Idx][j_57455].size)) break L7;
									j_57455 -= 1;
								}
						} while(false);
						if ((j_57455 <= i_57454)) {
						break L2;
						}
						else {
							var Tmp8 = list_57440[list_57440_Idx][i_57454]; list_57440[list_57440_Idx][i_57454] = list_57440[list_57440_Idx][j_57455]; list_57440[list_57440_Idx][j_57455] = Tmp8;							i_57454 += 1;
							j_57455 -= 1;
						}
						
					}
			} while(false);
			quicksort_57436(list_57440, list_57440_Idx, left_57441, (i_57454 - 1));
			quicksort_57436(list_57440, list_57440_Idx, (j_57455 + 1), right_57442);
		}
		}
	} while (false);

	
}

function getContext2D_56513(c_56515) {
	var result_56516 = null;

		result_56516=c_56515.getContext('2d');

	return result_56516;

}

function fillStyleeq__56089(ctx_56091, color_56092) {
		ctx_56091.fillStyle=color_56092;

	
}

function cls_57050(ctx_57052, width_57053, height_57054, color_57055) {
		fillStyleeq__56089(ctx_57052, color_57055);
		ctx_57052.fillRect(0.0, 0.0, width_57053, height_57054);

	
}

function draw_57010(ctx_57012, snow_57013) {
		fillStyleeq__56089(ctx_57012, snow_57013.color);
		ctx_57012.beginPath();
		ctx_57012.arc(snow_57013.pt.x, snow_57013.pt.y, (snow_57013.size / 2.0000000000000000e+000), 0.0, 6.2831853071795862e+000, true);
		ctx_57012.fill();

	
}

function setElements_42116(t_42119, ax_42120, ay_42121, bx_42122, by_42123, tx_42124, ty_42125) {
		t_42119.ax = ax_42120;
		t_42119.ay = ay_42121;
		t_42119.bx = bx_42122;
		t_42119.by = by_42123;
		t_42119.tx = tx_42124;
		t_42119.ty = ty_42125;

	
}

function move_42178(dx_42180, dy_42181) {
	var result_42182 = [{ax: 0.0, ay: 0.0, bx: 0.0, by: 0.0, tx: 0.0, ty: 0.0}];

		setElements_42116(result_42182[0], 1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000, dx_42180, dy_42181);

	return result_42182[0];

}

function ampeq__42959(p_42962, t_42963) {
		var newx_42964 = (((p_42962.x * t_42963.ax) + (p_42962.y * t_42963.bx)) + t_42963.tx);
		p_42962.y = (((p_42962.x * t_42963.ay) + (p_42962.y * t_42963.by)) + t_42963.ty);
		p_42962.x = newx_42964;

	
}

function minuseq__42738(x_42743, x_42743_Idx, y_42745) {
		x_42743[x_42743_Idx] = (x_42743[x_42743_Idx] - y_42745);

	
}

function move_57016(snow_57018, width_57019, height_57020) {
		var dx_57023 = (random_48318(1.0000000000000000e+000) * 3.0000000000000000e+000);
		var dy_57024 = (random_48318(1.0000000000000000e+000) * 5.0000000000000000e+000);
		var m_57025 = move_42178(dx_57023, dy_57024);
		ampeq__42959(snow_57018.pt, m_57025);
		if ((width_57019 < snow_57018.pt.x)) {
		minuseq__42738(snow_57018.pt, "x", width_57019);
		}
		
		if ((height_57020 < snow_57018.pt.y)) {
		minuseq__42738(snow_57018.pt, "y", height_57020);
		}
		

	
}

function loop_57056(canvas_57058, snows_57060) {
		var width_57062 = canvas_57058.width;
		var height_57063 = canvas_57058.height;
		var ctx_57064 = getContext2D_56513(canvas_57058);
		cls_57050(ctx_57064, width_57062, height_57063, "#0D0015");
		L1: do {
			var snow_57202 = null;
			var i_57209 = 0;
			var L_57211 = (snows_57060 != null ? snows_57060.length : 0);
			L2: do {
					L3: while (true) {
					if (!(i_57209 < L_57211)) break L3;
						snow_57202 = snows_57060[i_57209];
						draw_57010(ctx_57064, snow_57202);
						move_57016(snow_57202, width_57062, height_57063);
						i_57209 += 1;
					}
			} while(false);
		} while(false);

	
}

function main_57521() {

		function colonanonymous__57555() {
				loop_57056(canvas_57553, snows_57536[0]);

			
		}

		var snows_57536 = [makeSnow_57212(100, 1.0000000000000000e+003, 5.0000000000000000e+002)];
		quicksort_57436(snows_57536, 0, 0, (snows_57536[0] != null ? (snows_57536[0].length-1) : -1));
		var canvas_57553 = document.getElementById("snow");
		canvas_57553.width = 1000;
		canvas_57553.height = 500;
		var timer_57557 = window.setInterval(colonanonymous__57555, 16);

	
}
main_57521();

function matrix2d_42040(ax_42042, ay_42043, bx_42044, by_42045, tx_42046, ty_42047) {
	var result_42134 = [{ax: 0.0, ay: 0.0, bx: 0.0, by: 0.0, tx: 0.0, ty: 0.0}];

		setElements_42116(result_42134[0], ax_42042, ay_42043, bx_42044, by_42045, tx_42046, ty_42047);

	return result_42134[0];

}

function vector2d_42048(x_42050, y_42051) {
	var result_42319 = {x: 0.0, y: 0.0};

		result_42319.x = x_42050;
		result_42319.y = y_42051;

	return result_42319;

}
